version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wos
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wos-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - wos-net

  backend:
    build: .
    container_name: backend
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      Database__Host: "mysql:3306"
      Database__Password: "rootpassword"
      Redis__Host: "redis:6379"
    volumes:
      - shared_assets:/app/shared-assets
    networks:
      - wos-net

  frontend:
    build: ./dashboard
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - wos-net

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper
    depends_on:
      - mysql
    environment:
      Database__Host: "mysql:3306"
      Database__Password: "rootpassword"
    volumes:
      - shared_assets:/app/shared-assets
    networks:
      - wos-net

volumes:
  mysql_data:
  shared_assets:

networks:
  wos-net:
    driver: bridge