ALTER TABLE players
DROP COLUMN avail_0200 BOOLEAN DEFAULT FALSE,
DROP COLUMN avail_1200 BOOLEAN DEFAULT FALSE,
DROP COLUMN avail_1400 BOOLEAN DEFAULT FALSE,
DROP COLUMN avail_1900 BOOLEAN DEFAULT FALSE,
ADD COLUMN tundra_availability ENUM('Full','Partial','Unavailable') DEFAULT 'Unavailable';