ALTER TABLE players
DROP COLUMN tundra_availability,
ADD COLUMN avail_0200 BOOLEAN DEFAULT FALSE,
ADD COLUMN avail_1200 BOOLEAN DEFAULT FALSE,
ADD COLUMN avail_1400 BOOLEAN DEFAULT FALSE,
ADD COLUMN avail_1900 BOOLEAN DEFAULT FALSE;