INSERT IGNORE INTO buildings (internal_id, type) VALUES
(1, 'Fortress'),
(2, 'Fortress'),
(3, 'Fortress'),
(4, 'Fortress'),
(5, 'Fortress'),
(6, 'Fortress'),
(7, 'Fortress'),
(8, 'Fortress'),
(9, 'Fortress'),
(10, 'Fortress'),
(11, 'Fortress'),
(12, 'Fortress'),
(1, 'Stronghold'),
(2, 'Stronghold'),
(3, 'Stronghold'),
(4, 'Stronghold');

INSERT IGNORE INTO building_rewards (building_id, week_number, reward_name, reward_icon) VALUES
-- week 1
(1, 1, 'Old Wheel Hero', 'shard.png'),
(2, 1, 'Advanced Teleport', 'teleport.png'),
(3, 1, 'General Speedups', 'speedups.png'),
(4, 1, 'Health Buff', 'health_buff.png'),
(5, 1, 'Old Wheel Hero', 'shard.png'),
(6, 1, 'Advanced Teleport', 'teleport.png'),
(7, 1, 'General Speedups', 'speedups.png'),
(8, 1, 'Lethality Buff', 'lethality_buff.png'),
(9, 1, 'Old Wheel Hero', 'shard.png'),
(10, 1, 'Advanced Teleport', 'teleport.png'),
(11, 1, 'General Speedups', 'speedups.png'),
(12, 1, 'Deployment Buff', 'deployment_buff.png'),
(13, 1, 'Old KoI Hero', 'shard.png'),
(14, 1, 'Fire Crystals', 'fcrystal.png'),
(15, 1, 'Hero Gear Chest', 'chest.png'),
(16, 1, 'Pet Chest', 'pet.png'),
-- week 2
(1, 2, 'Health Buff', 'health_buff.png'),
(2, 2, 'Old Wheel Hero', 'shard.png'),
(3, 2, 'Advanced Teleport', 'teleport.png'),
(4, 2, 'General Speedups', 'speedups.png'),
(5, 2, 'Lethality Buff', 'lethality_buff.png'),
(6, 2, 'Old Wheel Hero', 'shard.png'),
(7, 2, 'Advanced Teleport', 'teleport.png'),
(8, 2, 'General Speedups', 'speedups.png'),
(9, 2, 'Deployment Buff', 'deployment_buff.png'),
(10, 2, 'Old Wheel Hero', 'shard.png'),
(11, 2, 'Advanced Teleport', 'teleport.png'),
(12, 2, 'General Speedups', 'speedups.png'),
(13, 2, 'Pet Chest', 'pet.png'),
(14, 2, 'Old KoI Hero', 'shard.png'),
(15, 2, 'Fire Crystals', 'fcrystal.png'),
(16, 2, 'Hero Gear Chest', 'chest.png'),
-- week 3
(1, 3, 'General Speedups', 'speedups.png'),
(2, 3, 'Health Buff', 'health_buff.png'),
(3, 3, 'Old Wheel Hero', 'shard.png'),
(4, 3, 'Advanced Teleport', 'teleport.png'),
(5, 3, 'General Speedups', 'speedups.png'),
(6, 3, 'Lethality Buff', 'lethality_buff.png'),
(7, 3, 'Old Wheel Hero', 'shard.png'),
(8, 3, 'Advanced Teleport', 'teleport.png'),
(9, 3, 'General Speedups', 'speedups.png'),
(10, 3, 'Deployment Buff', 'deployment_buff.png'),
(11, 3, 'Old Wheel Hero', 'shard.png'),
(12, 3, 'Advanced Teleport', 'teleport.png'),
(13, 3, 'Hero Gear Chest', 'chest.png'),
(14, 3, 'Pet Chest', 'pet.png'),
(15, 3, 'Old KoI Hero', 'shard.png'),
(16, 3, 'Fire Crystals', 'fcrystal.png'),
-- week 4
(1, 4, 'Advanced Teleport', 'teleport.png'),
(2, 4, 'Enhancement XP Component', 'enhancement.png'),
(3, 4, 'Health Buff', 'health_buff.png'),
(4, 4, 'TBC1', 'TBC1.png'),
(5, 4, 'TBC1', 'TBC1.png'),
(6, 4, 'General Speedups', 'speedups.png'),
(7, 4, 'Advanced Teleport', 'teleport.png'),
(8, 4, 'Enhancement XP Component', 'enhancement.png'),
(9, 4, 'Lethality Buff', 'lethality_buff.png'),
(10, 4, 'TBC1', 'TBC1.png'),
(11, 4, 'TBC1', 'TBC1.png'),
(12, 4, 'General Speedups', 'speedups.png'),
(13, 4, 'Old Wheel Hero', 'shard.png'),
(14, 4, 'Fire Crystals', 'fcrystal.png'),
(15, 4, 'Pet Chest', 'pet.png'),
(16, 4, 'Old KoI Hero', 'shard.png'),
-- week 5
(1, 5, 'Pet Stones', 'pet_stone.png'),
(2, 5, 'Enhancement XP Component', 'enhancement.png'),
(3, 5, 'General Speedups', 'speedups.png'),
(4, 5, 'Advanced Teleport', 'teleport.png'),
(5, 5, 'Pet Stones', 'pet_stone.png'),
(6, 5, 'Enhancement XP Component', 'enhancement.png'),
(7, 5, 'General Speedups', 'speedups.png'),
(8, 5, 'Advanced Teleport', 'teleport.png'),
(9, 5, 'Pet Stones', 'pet_stone.png'),
(10, 5, 'Enhancement XP Component', 'enhancement.png'),
(11, 5, 'General Speedups', 'speedups.png'),
(12, 5, 'Advanced Teleport', 'teleport.png'),
(13, 5, 'Old KoI Hero', 'shard.png'),
(14, 5, 'Fire Crystals', 'fcrystal.png'),
(15, 5, 'Hero Gear Chest', 'chest.png'),
(16, 5, 'Pet Chest', 'pet.png'),
-- week 6
(1, 6, 'Health Buff', 'health_buff.png'),
(2, 6, 'Pet Stones', 'pet_stone.png'),
(3, 6, 'Enhancement XP Component', 'enhancement.png'),
(4, 6, 'General Speedups', 'speedups.png'),
(5, 6, 'Lethality Buff', 'lethality_buff.png'),
(6, 6, 'Pet Stones', 'pet_stone.png'),
(7, 6, 'Enhancement XP Component', 'enhancement.png'),
(8, 6, 'General Speedups', 'speedups.png'),
(9, 6, 'Deployment Buff', 'deployment_buff.png'),
(10, 6, 'Pet Stones', 'pet_stone.png'),
(11, 6, 'Enhancement XP Component', 'enhancement.png'),
(12, 6, 'General Speedups', 'speedups.png'),
(13, 6, 'Pet Chest', 'pet.png'),
(14, 6, 'Old KoI Hero', 'shard.png'),
(15, 6, 'Fire Crystals', 'fcrystal.png'),
(16, 6, 'Hero Gear Chest', 'chest.png'),
-- week 7
(1, 7, 'General Speedups', 'speedups.png'),
(2, 7, 'Health Buff', 'health_buff.png'),
(3, 7, 'Pet Stones', 'pet_stone.png'),
(4, 7, 'Enhancement XP Component', 'enhancement.png'),
(5, 7, 'General Speedups', 'speedups.png'),
(6, 7, 'Lethality Buff', 'lethality_buff.png'),
(7, 7, 'Pet Stones', 'pet_stone.png'),
(8, 7, 'Enhancement XP Component', 'enhancement.png'),
(9, 7, 'General Speedups', 'speedups.png'),
(10, 7, 'Deployment Buff', 'deployment_buff.png'),
(11, 7, 'Pet Stones', 'pet_stone.png'),
(12, 7, 'Enhancement XP Component', 'enhancement.png'),
(13, 7, 'Hero Gear Chest', 'chest.png'),
(14, 7, 'Pet Chest', 'pet.png'),
(15, 7, 'Fire Crystals', 'fcrystal.png'),
(16, 7, 'Old KoI Hero', 'shard.png'),
-- week 8
(1, 8, 'Enhancement XP Component', 'enhancement.png'),
(2, 8, 'General Speedups', 'speedups.png'),
(3, 8, 'Health Buff', 'health_buff.png'),
(4, 8, 'Pet Stones', 'pet_stone.png'),
(5, 8, 'Enhancement XP Component', 'enhancement.png'),
(6, 8, 'General Speedups', 'speedups.png'),
(7, 8, 'Lethality Buff', 'lethality_buff.png'),
(8, 8, 'Pet Stones', 'pet_stone.png'),
(9, 8, 'Enhancement XP Component', 'enhancement.png'),
(10, 8, 'General Speedups', 'speedups.png'),
(11, 8, 'Deployment Buff', 'deployment_buff.png'),
(12, 8, 'Pet Stones', 'pet_stone.png'),
(13, 8, 'Old Wheel Hero', 'shard.png'),
(14, 8, 'Fire Crystals', 'fcrystal.png'),
(15, 8, 'Pet Chest', 'pet.png'),
(16, 8, 'Old KoI Hero', 'shard.png');